group:
  - repos: |
      purelyfortesting/dest
    files:
      - source: .pre-commit-config.yaml.jinja
        dest: .pre-commit-config.yaml
        template: true
      - source: .pre-commit-config.frontend.yaml.jinja
        dest: .pre-commit-config.frontend.yaml
        template: true
