name: Sync files

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run file sync
        uses: BetaHuhn/repo-file-sync-action@v1.18.0
        with:
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
